/*
 * generated by Xtext
 */
package org.xtext.emn.selenium.ui.contentassist

import org.xtext.emn.selenium.ui.contentassist.AbstractSELProposalProvider

/**
 * See https://www.eclipse.org/Xtext/documentation/304_ide_concepts.html#content-assist
 * on how to customize the content assistant.
 */
class SELProposalProvider extends AbstractSELProposalProvider {
}
