/*
 * generated by Xtext
 */
package org.xtext.emn.selenium.serializer;

import com.google.inject.Inject;
import java.util.List;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.xtext.IGrammarAccess;
import org.eclipse.xtext.RuleCall;
import org.eclipse.xtext.nodemodel.INode;
import org.eclipse.xtext.serializer.analysis.GrammarAlias.AbstractElementAlias;
import org.eclipse.xtext.serializer.analysis.GrammarAlias.GroupAlias;
import org.eclipse.xtext.serializer.analysis.GrammarAlias.TokenAlias;
import org.eclipse.xtext.serializer.analysis.ISyntacticSequencerPDAProvider.ISynNavigable;
import org.eclipse.xtext.serializer.analysis.ISyntacticSequencerPDAProvider.ISynTransition;
import org.eclipse.xtext.serializer.sequencer.AbstractSyntacticSequencer;
import org.xtext.emn.selenium.services.SELGrammarAccess;

@SuppressWarnings("all")
public class SELSyntacticSequencer extends AbstractSyntacticSequencer {

	protected SELGrammarAccess grammarAccess;
	protected AbstractElementAlias match_Condition_NotKeyword_0_q;
	protected AbstractElementAlias match_IfThenElse___ElseKeyword_5_0_RightCurlyBracketKeyword_5_2__q;
	
	@Inject
	protected void init(IGrammarAccess access) {
		grammarAccess = (SELGrammarAccess) access;
		match_Condition_NotKeyword_0_q = new TokenAlias(false, true, grammarAccess.getConditionAccess().getNotKeyword_0());
		match_IfThenElse___ElseKeyword_5_0_RightCurlyBracketKeyword_5_2__q = new GroupAlias(false, true, new TokenAlias(false, false, grammarAccess.getIfThenElseAccess().getElseKeyword_5_0()), new TokenAlias(false, false, grammarAccess.getIfThenElseAccess().getRightCurlyBracketKeyword_5_2()));
	}
	
	@Override
	protected String getUnassignedRuleCallToken(EObject semanticObject, RuleCall ruleCall, INode node) {
		return "";
	}
	
	
	@Override
	protected void emitUnassignedTokens(EObject semanticObject, ISynTransition transition, INode fromNode, INode toNode) {
		if (transition.getAmbiguousSyntaxes().isEmpty()) return;
		List<INode> transitionNodes = collectNodes(fromNode, toNode);
		for (AbstractElementAlias syntax : transition.getAmbiguousSyntaxes()) {
			List<INode> syntaxNodes = getNodesFor(transitionNodes, syntax);
			if(match_Condition_NotKeyword_0_q.equals(syntax))
				emit_Condition_NotKeyword_0_q(semanticObject, getLastNavigableState(), syntaxNodes);
			else if(match_IfThenElse___ElseKeyword_5_0_RightCurlyBracketKeyword_5_2__q.equals(syntax))
				emit_IfThenElse___ElseKeyword_5_0_RightCurlyBracketKeyword_5_2__q(semanticObject, getLastNavigableState(), syntaxNodes);
			else acceptNodes(getLastNavigableState(), syntaxNodes);
		}
	}

	/**
	 * Ambiguous syntax:
	 *     'Not'?
	 *
	 * This ambiguous syntax occurs at:
	 *     (rule start) (ambiguity) elem=Elem
	 *     (rule start) (ambiguity) op=UnaryOp
	 */
	protected void emit_Condition_NotKeyword_0_q(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
	/**
	 * Ambiguous syntax:
	 *     ('Else {' '}')?
	 *
	 * This ambiguous syntax occurs at:
	 *     condition=Condition '{' '}' (ambiguity) (rule end)
	 *     then+=Instruction '}' (ambiguity) (rule end)
	 */
	protected void emit_IfThenElse___ElseKeyword_5_0_RightCurlyBracketKeyword_5_2__q(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
}
