/*
 * generated by Xtext
 */
package org.xtext.emn.selenium.ui;

import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

import com.google.inject.Injector;

import org.xtext.emn.selenium.ui.internal.SELActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class SELExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return SELActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return SELActivator.getInstance().getInjector(SELActivator.ORG_XTEXT_EMN_SELENIUM_SEL);
	}
	
}
