/*
 * generated by Xtext
 */
package org.xtext.emn.selenium.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class SELUiModule extends org.xtext.emn.selenium.ui.AbstractSELUiModule {
	public SELUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
