/*
 * generated by Xtext
 */
package org.xtext.emn.selenium;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class SELRuntimeModule extends org.xtext.emn.selenium.AbstractSELRuntimeModule {

}
