/*
 * generated by Xtext
 */
package org.xtext.emn.selenium;

/**
 * Initialization support for running Xtext languages 
 * without equinox extension registry
 */
public class SELStandaloneSetup extends SELStandaloneSetupGenerated{

	public static void doSetup() {
		new SELStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}

