/*
 * generated by Xtext
 */
package org.xtext.emn.selenium;

import org.eclipse.xtext.junit4.IInjectorProvider;

import com.google.inject.Injector;

public class SELUiInjectorProvider implements IInjectorProvider {
	
	@Override
	public Injector getInjector() {
		return org.xtext.emn.selenium.ui.internal.SELActivator.getInstance().getInjector("org.xtext.emn.selenium.SEL");
	}
	
}
